### ISSUE TITLE
Drachtio-Server doesn't send ACK to 200 OK Message

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-server#41]
Hi, I am trying to use drachtio as a B2BUA with Rtpengine, everything works fine except 2 minor problems.

1, When trunk sends 200 OK with SDP, I think drachtio should send ACK message, here is a sample log from drachtio-server (192.168.0.87)
![image](https://user-images.githubusercontent.com/4982519/42926557-75691322-8b3a-11e8-8a6e-553a27d6f569.png)

And here is eyebeam softphone with same trunk (192.168.1.50)
![image](https://user-images.githubusercontent.com/4982519/42926613-a1a108a0-8b3a-11e8-965b-43fc67c23b06.png)

2. When creating rtpengine and b2bua, cannot create uas object but rtp and sip works, when destroying call, since it cannot find uas object, call cannot be disconnected automatically.
Here is Error:

> Error proxying call with media: TypeError: Cannot destructure property `uas` of 'undefined' or 'null'.: TypeError: Cannot destructure property `uas` of 'undefined' or 'null'.
    at rtpengine.offer.then.then.then (C:\TFS\vcp\vcp.B2BUAVirtualPbx\app.js:266:19)

Here is Code:
    
```
        dest = `sip:${uri.user}@${config.get('destination')}`;
        var trunk = config.get("trunks")[0];
        //dest = `sip:${config.get('FromAccount')}@${config.get('destination')}`

        //req.callingNumber = config.get('FromAccount');

        rtpengine.offer(locRtp, Object.assign(details, { 'sdp': req.body, 'record call': 'yes' }))
            .then((rtpResponse) => {
                console.log(`got response from rtpengine: ${JSON.stringify(rtpResponse)}`);
                if (rtpResponse && rtpResponse.result === 'ok') return rtpResponse.sdp;
                throw new Error('rtpengine failure');
            })
            .then((sdpB) => {
                console.log(`rtpengine offer returned sdp ${sdpB}`);
                return srf.createB2BUA(req, res, dest, {
                    localSdpB: sdpB,
                    localSdpA: getSdpA.bind(null, details),
                    auth: {
                        username: trunk.username,
                        password: trunk.password
                    }
                })
                .catch((err) => {
                    console.log(`Error connecting call: ${err.message}`);
                });
            })
            .then(({ uas, uac }) => {
                console.log('call connected with media proxy');

                return endCall(uas, uac, details);
            })
            .catch((err) => {
                console.error(`Error proxying call with media: ${err}: ${err.stack}`);
            });
```

**Comment by davehorton** [comment]
can you include the full drachtio server log for your call ?  I came across an issue myself yesterday that was similar, except that the issue was the drachtio app *did* generate an ACK but it had the wrong .tag on the From header.  Your scenario does not show an ACK at all though, which is strange

**Comment by davehorton** [comment]
can you retest with drachtio 4.3.3 (just published)?

There is a bug fix for the B2B or UAC scenario when an auth challenge is made and I think this bug was affecting you.

**Comment by davehorton** [comment]
Also, could you please test with the latest drachtio-server (develop branch) which is tag v0.7.3-rc4.  If you are using docker you can get it with `docker pull drachtio/drachtio-server:latest`

**Comment by salihy** [comment]
I will test and let you know.

**Comment by salihy** [comment]
I updated both drachtio-server and drachtio-srf and now I have a different problem, it was working in previous version. I connect to sip trunk when application starting, with updated version, it is unable to connect sip trunk, you can find logs attached.

![image](https://user-images.githubusercontent.com/4982519/42986095-f31fe6ca-8bfc-11e8-817c-460308d25bba.png)


After 401 Unauthorized message, drachtio should have sent a new Register message with authentication information:
![image](https://user-images.githubusercontent.com/4982519/42985798-a71fe154-8bfb-11e8-97d1-de6af378d88f.png)

[log5.zip](https://github.com/davehorton/drachtio-server/files/2212665/log5.zip)

Sample working softphone flow:
![image](https://user-images.githubusercontent.com/4982519/42986006-92b20084-8bfc-11e8-961b-b3f8db8f4a30.png)




Code:
```
srf.connect(config.get('drachtio'))
    .on('connect', (err, hostport) => {
        if (err) {
            return console.error(`error connecting: ${err.message}`);
        }

        var trunk = config.get("trunks")[0];
        srf.request({
            uri: `sip:${trunk.ip}:${trunk.port}`,
            method: "REGISTER",
            headers: {
                "Contact": `sip:${trunk.did}@${trunk.ip}:${trunk.port}`,
                "To": `"${trunk.did}"<sip:${trunk.username}@${trunk.ip}:${trunk.port}>`,
                "From": `"${trunk.did}"<sip:${trunk.username}@${trunk.ip}:${trunk.port}>`,
                "User-Agent": "viases-pbx",
                //"Allow": "INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO"
            },
            auth: {
                username: trunk.username,
                password: trunk.password
            }
        }, function (err, req) {
            if (err) {
                throw err;
            }
            req.on("response", function (res) {
                if (res.status < 200) {
                    console.log("Response " + res.status)
                    return;
                }
                if (200 !== res.msg.status) {
                    console.log("Error registering: " + res.msg.status);
                } else {
                    console.log("registered successfully");
                }
            });
        });

        console.log(`connected hostport: ${hostport}`);
    })
    .on('error', (err) => {
        console.log(`Error connecting: ${err}`);
    });
```

**Comment by salihy** [comment]
When I downgraded only drachtio-server it can authenticate.

![image](https://user-images.githubusercontent.com/4982519/42998672-a16e0e5c-8c23-11e8-9810-ac6602327b0c.png)

**Comment by davehorton** [comment]
Yikes!  Thanks for catching that bug in my latest drachtio-server checkin.  Just committed a fix, building now..

**Comment by davehorton** [comment]
I've rebuilt the docker image, would you be able to re-run your tests now with the latest image and verify everything works properly?

**Comment by salihy** [comment]
Sorry for late response, it gives another error now when registering, I didn't use docker image, I just cloned repo and build with your instructions on debian 9.

![image](https://user-images.githubusercontent.com/4982519/43059292-77c6604e-8e54-11e8-8fe2-c88f31f876f0.png)
![image](https://user-images.githubusercontent.com/4982519/43059311-89b94bd6-8e54-11e8-994a-7fbf3d470ca5.png)

**Comment by davehorton** [comment]
with your build can you give me the output of `drachtio --version`

**Comment by salihy** [comment]
it is v0.7.3-rc2-4-g69a24f8bf

**Comment by salihy** [comment]
I also ran `drachtio --version` in docker container, it is also v0.7.3-rc2-4-g69a24f8

**Comment by davehorton** [comment]
can you rebuild now on debian with latest on develop and re-test?

**Comment by salihy** [comment]
Building now.

**Comment by salihy** [comment]
First problem continues.

![image](https://user-images.githubusercontent.com/4982519/43064076-8fd76ad6-8e66-11e8-84a4-ac0a809171e0.png)

**Comment by davehorton** [comment]
Sorry for this....not sure why I am having such trouble getting this simple fix committed correctly!

Can you retest one more time with the latest fix to drachtio-server, just committed.

**Comment by salihy** [comment]
It's still the same, is there any way I can help you more with this problem? 

[log10.zip](https://github.com/davehorton/drachtio-server/files/2222008/log10.zip)

```
salih@salihy:~$ /usr/local/bin/drachtio --version
v0.7.3-rc2-6-gf3c6c934c
```
![image](https://user-images.githubusercontent.com/4982519/43117873-c988a0c2-8f17-11e8-993c-5973d8c7d9e4.png)

**Comment by davehorton** [comment]
Can you run it on the debian build you do your self and send me a zip of the entire drachtio server log file?

**Comment by davehorton** [comment]
also, after pulling the latest please make sure to 
```
git submodule update --init --recursive
```
as the fix is in the sofia-sip submodule.
cd into 'deps/sofia-sip' and verify the latest commit by doing
```
git log
```
the most recent commit should be:
```
commit f3c6c934cfc9db8274165a2b93595108812aa8e2 (HEAD -> develop, origin/develop)
Author: Dave Horton <daveh@beachdognet.com>
Date:   Mon Jul 23 20:30:38 2018 +0100

    yet another update to the sofia fix
```

**Comment by salihy** [comment]
You can fin log file attached below.

[logs.tar.gz](https://github.com/davehorton/drachtio-server/files/2222505/logs.tar.gz)

**Comment by salihy** [comment]
Ok, I saw a problem in drachtio.log file, when I send invite request, drachtio sends twice because authentication is required. 

When I look at pcap log file, I see that 2nd INVITE requests sequence number is `125868052`, but when I look at drachtio.log file, it shows all 200 OK responses request numbers `125868051` (this is first invites sequence number). I think drachtio somehow cannot obtain correct sequence numbers.

![image](https://user-images.githubusercontent.com/4982519/43124625-58c167f2-8f30-11e8-9c4d-0957aa7e0b6c.png)
![image](https://user-images.githubusercontent.com/4982519/43124662-70a57124-8f30-11e8-8f1b-6e0f6d73fd40.png)

Drachtio.log ok message:

```
2018-07-24 10:34:34.559673 recv 659 bytes from udp/[185.86.153.82]:5060 at 10:34:34.559539:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.87;received=31.145.97.187;rport=5060;branch=z9hG4bKjXpamrmy3y50H
Record-Route: <sip:185.86.153.82;ftag=NvejaD076y98F;lr>
From: <sip:908507070619@192.168.0.87:5060>;tag=NvejaD076y98F
To: <sip:05323762168@185.86.153.82>;tag=119f7ab01a6c5c9c8ead0d5744579d39
Call-ID: cb352b49-09b6-1237-74bc-000c2981f69d
CSeq: 125872761 INVITE
Server: Sippy Softswitch
Contact: Anonymous <sip:185.86.153.82:5061>
Content-Length: 161
Content-Type: application/sdp

v=0
o=- 13055245226 13055245226 IN IP4 178.251.41.101
s=-
t=0 0
m=audio 61840 RTP/AVP 18 0 8 101
c=IN IP4 185.86.153.82
a=rtpmap:101 telephone-event/8000 
```

**Comment by davehorton** [comment]
did you definitely run `git submodule update --init --recursive` from the base directory after you checked out the latest?  Your sofia-sip directory does not have the correct commit, so either you have not updated the submodule after doing `git pull` into an existing directory, or I have not checked in the commit to the submodule properly

**Comment by salihy** [comment]
I am definitely sure I run this. Everytime I try, I delete all the repo and clone again and run all the commands below. I also checked the commits sofia-sip library in github, it is the same.

https://github.com/davehorton/sofia-sip/commits/master

```
git clone --depth=50 --branch=develop git://github.com/davehorton/drachtio-server.git && cd drachtio-server
git submodule update --init --recursive
./bootstrap.sh
mkdir build && cd $_
../configure CPPFLAGS='-DNDEBUG'
make
sudo make install
```

**Comment by davehorton** [comment]
The last commit in sofia-sip is this

```
MacBook-Pro-4:sofia-sip dhorton$ git log --oneline
13d48e7d (HEAD -> master, origin/master, origin/HEAD) sigh..hopefully final fix for making sure new msg created by nta_outgoing_tcreate() has a tag on From equal to local tag of leg
```

and that looks to me to be the sofia-sip commit that the head of the develop branch is using.  Do you see it differently?

On Jul 24, 2018, at 6:41 PM, Salih YILDIRIM <notifications@github.com> wrote:

I am definitely sure I run this. Everytime I try, I delete all the repo and clone again and run all the commands below. I also checked the commits sofia-sip library in github, it is the same.

https://github.com/davehorton/sofia-sip/commits/master <https://github.com/davehorton/sofia-sip/commits/master>
git clone --depth=50 --branch=develop git://github.com/davehorton/drachtio-server.git && cd drachtio-server
git submodule update --init --recursive
./bootstrap.sh
mkdir build && cd $_
../configure CPPFLAGS='-DNDEBUG'
make
sudo make install

**Comment by salihy** [comment]
It’s same. You can see above my git log outputs

**Comment by davehorton** [comment]
ok, will have a look at your logs.  Sorry for the slow turnaround on this, I am on holiday this week

**Comment by davehorton** [comment]
ok, I think I may see the problem, and it is different than what I thought (though I think the fix I applied may have been necessary as well).

The key error line in the logs is this:

`2018-07-24 10:34:09.345601 nta.c:8473 outgoing_try_tcp_instead() nta: INVITE (125872761) too large for UDP, trying TCP`

can you edit your drachtio.conf.xml file to add this tag in the <sip> section:

<udp-mtu>4096</udp-mtu>

See the release notes related to that here: https://drachtio.org/releases?type=drachtio-server&page=2

the size of the message is forcing it to attempt tcp first, when that fails it falls back to udp but then for the ACK it attempts tcp again and fails.  Can you set the udp mtu threshold larger, as per above and then retry?

**Comment by salihy** [comment]
Thanks, it worked. Don't worry with late response, have fun.

![image](https://user-images.githubusercontent.com/4982519/43179739-1a308998-8fdd-11e8-9832-19ed94610089.png)
